#!/bin/sh

BUNDLES=$(cat <<HERE
https://github.com/groenewege/vim-less.git
https://github.com/kchmck/vim-coffee-script.git
https://github.com/editorconfig/editorconfig-vim.git
https://github.com/tpope/vim-fireplace.git
https://github.com/tpope/vim-classpath.git
https://github.com/guns/vim-clojure-static.git
https://github.com/puppetlabs/puppet-syntax-vim.git
https://github.com/pangloss/vim-javascript.git
https://github.com/mxw/vim-jsx.git
HERE
)

mkdir -p bundle

for i in $BUNDLES; do
  REPO=$(echo $i | cut -d '/' -f 5 | rev | cut -b 5- | rev)
  if [ -d bundle/$REPO ]; then
    (cd bundle/$REPO; git pull)
  else
    (cd bundle; git clone $i)
  fi
done
